import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Lora, Playfair_Display, Space_Mono } from "next/font/google";
import "../styles/globals.css";
import Header from "../components/layout/header/Header";
import Footer from "../components/layout/footer/Footer";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter"
})
const lora = Lora({ 
  subsets: ["latin"], 
  variable: "--font-lora" 
})
const spaceMono = Space_Mono({ 
  subsets: ["latin"], 
  weight: ["400", "700"], 
  variable: "--font-space-mono" 
})
const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-display',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className= {`bg-background text-foreground ${inter.className}`}>
        <Header />
        <div className="pt-16 lg:pt-20 ">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
