import { Inter, Lora, Playfair_Display, Space_Mono } from "next/font/google";
import "@/src/styles/globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/src/i18n/routing";
import { notFound } from "next/navigation";
import CompanyInfoSRV from "@/src/components/CompanyInfo/CompanyInfoSRV";
import Header from "@/src/components/Layout/Header/Header";
import Footer from "@/src/components/Layout/Footer/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter"
})

export default async function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang="en">
      <body className={`bg-background text-foreground ${inter.className}`}>
        <CompanyInfoSRV />
        <NextIntlClientProvider>
          <Header />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
